### ISSUE TITLE
Crash when opening web_connectivity test result

### ISSUE THREAD

**Issue by hellais** [measurement-kit/netprobe-ios#37]
When opening the web_connectivity test results the app will crash.

This only happens when there is no result and it's due to a off-by-one error in the view results.

@bassosimone has pushed a fix for this inside of https://github.com/measurement-kit/netprobe-ios/commit/0ddc01bd477a3696485e5575b301809313396ab2

**Comment by lorenzoPrimi** [comment]
does this still happen? @bassosimone @hellais

**Comment by bassosimone** [comment]
No, it should have been fixed in fe128ad39b1. I'd say we open this issue again if we noticed the bug again but afaik it has been fixed.
