### ISSUE TITLE
When the wrong answer is provided to the quiz, you are not redirected to the risks page

### ISSUE THREAD

**Issue by hellais** [measurement-kit/netprobe-ios#41]
If I don't answer correctly to the quiz in step 3 I am not redirected to step 2, like in the desktop quiz, but instead I am on the same page.

**Comment by lorenzoPrimi** [comment]
fixed in https://github.com/measurement-kit/netprobe-ios/commit/bfcb452d401d1dfa4662609a277bc991d9031eab
