### ISSUE TITLE
The checkboxes in the configuration don't look like checkboxes

### ISSUE THREAD

**Issue by hellais** [measurement-kit/netprobe-ios#42]
In the last step of the setup wizard the boxes to indicate the customizable configuration options look like radio's (choose one option of many) instead they should look like checkboxes (toggle on and off).

**Comment by lorenzoPrimi** [comment]
fixed in https://github.com/measurement-kit/netprobe-ios/commit/bfcb452d401d1dfa4662609a277bc991d9031eab
